#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g angular-cli-ghpages
  - npm install -g @angular/cli

script:
  - npm run deploy

after_success:
  - angular-cli-ghpages --repo="https://$GH_TOKEN@github.com/pouyio/angular-http-demo.git" --name="pouyio" --email="pouyio@gmail.com"

notifications:
  email:
    on_failure: never
    on_success: never
